### ISSUE TITLE
Reference directories when using config file

### ISSUE THREAD

**Issue by alexmechanic** [blingenf/copydetect#15] opened 2022-05-15 21:04 UTC
It is told that if `reference_directories` list is empty, they become equal to `test_directories` list (which is strictly required in any variant).

But it is not told (at least it is not cleared out) that if using tool with `-c` flag, `reference_directories` list should be provided non-empty in config file and it will not become equal to (copied from) `test_directories` list.

And this 'cross-confusing rule' got confirmed when I've inspected the code [here](https://github.com/blingenf/copydetect/blob/master/copydetect/detector.py#L224) (copy) and [here](https://github.com/blingenf/copydetect/blob/a53eca506c67ede1ab17a9f5929b89cf3ecfe01c/copydetect/detector.py#L273) (no copy) that empty `reference_directories` is only allowed for full-optioned CLI run, but not with `-c`-run.

Can you state this restriction more clear in the docs or, probably better - update the `-c` mode to behave equal to full-optioned run?

**Comment by blingenf** [comment] 2022-05-15 21:37
I believe the configuration file also requires `noise_threshold`, `guarantee_threshold`, and `display_threshold` to be explicitly specified which is not true for the CLI. I don't remember my original reasoning for that, but the configuration definitely should behave identically to the CLI method. I'll adjust how the defaults are handled.

**Comment by alexmechanic** [comment] 2022-05-16 08:26
Thank you for quick response!

Maybe moving code before [reading config file](https://github.com/blingenf/copydetect/blob/master/copydetect/detector.py#L242) to place right after could help, but I cannot be sure as I did not dig into the sources much yet.

**Comment by blingenf** [comment] 2022-05-21 23:00
I decided it was best to deal with the root cause of this issue, which is allowing both a config file and specific parameters to be passed as arguments to the `CopyDetector` initializer. For future versions I'm planning on separating these two initialization methods. To initialize with a config file you would need `CopyDetector.from_config(config)`

The PR is here: https://github.com/blingenf/copydetect/pull/16. If this change would be particularly disruptive for your project feel free to comment on the PR.

**Comment by alexmechanic** [comment] 2022-05-22 09:48
It's not a big deal, I am ready to update my project once the new release is coming to the PyPi, since I am using this tool as the pip requirement.

**Comment by alexmechanic** [comment] 2022-05-22 09:52
Is it correct that from now API allows only 2 options: a) full config parameters set up and b) passing config **file** instead? So I need to save current config dict to file first and then pass the file path to process?

**Comment by blingenf** [comment] 2022-05-22 13:47
> Is it correct that from now API allows only 2 options: a) full config parameters set up and b) passing config **file** instead? So I need to save current config dict to file first and then pass the file path to process? Asking because the PR description says it's a config **file**, but from the code it's still a config **dict object** argument.

Sorry, the PR description could have been more clear. It's still a dict object, so you won't have to save it first.

**Comment by blingenf** [comment] 2022-05-29 22:32
The fix is in [version 0.4.1](https://github.com/blingenf/copydetect/releases/tag/0.4.1) and is now on pypi. Your existing code should still work but when you switch to the `from_config` function make sure to require `copydetect>=0.4.1`.

**Closed** 2022-08-14 19:55 UTC
Labels: bug
